#server:
#  port: 8081
spring:
  application:
    name: hmdp
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    stream:
      username: wy
      password: 112358
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 5
          multiplier: 2.0
          initial-interval: 1000ms
          max-interval: 20000ms
  datasource:
    url: jdbc:mysql://localhost:3306/hmdp
    username: root
    password: 112358
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug